name: Deploy Website to S3

on:
  push:
    branches:
      - main  # Trigger the workflow on changes to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set Up Node.js (for linting)
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    # Step 3: Install Dependencies
    - name: Install dependencies
      run: npm install

    # Step 4: HTML Validation
    - name: Validate HTML files
      uses: jakejarvis/html-proofer-action@v0.1.1
      with:
        args: ./index.html

    # Step 5: CSS Validation
    - name: Validate CSS files
      uses: w3c-validator/w3c-css-validator@v1.0.0
      with:
        file: "./style.css"  # Specify your CSS file(s)

    # Step 6: JavaScript Linting with ESLint
    - name: Lint JavaScript
      run: npx eslint script.js  # Replace with the path to your JS file(s)

    # Step 7: Configure AWS Credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1

    # Step 8: Deploy to S3
    - name: Deploy to S3
      run: |
        aws s3 sync . s3://my-cicd-webapp-bucket --delete
