name: Deploy Website to S3

on:
  push:
    branches:
      - main  # Trigger the workflow on changes to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Update to the latest version

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2  # Update to the latest version
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1

    - name: Deploy to S3
      run: |
        aws s3 sync . s3://my-cicd-webapp-bucket --delete
